### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/pyHDB#13]
Algumas melhorias ainda precisam ser feitas.

- [x] Incluir na documentação informações sobre o artigo publicado: BRASIL, Eric. pyHDB - Ferramenta Heurística para a Hemeroteca Digital Brasileira: utilizando técnicas de web scraping para a pesquisa em História. _História da Historiografia: International Journal of Theory and History of Historiography_, Ouro Preto, v. 15, n. 40, p. 186–217, 2022. DOI: [10.15848/hh.v15i40.1904](https://doi.org/10.15848/hh.v15i40.1904). Disponível em: https://www.historiadahistoriografia.com.br/revista/article/view/1904. Acesso em: 6 jan. 2023.
- [x] Cores no terminal para Windows (ver #10 ): incluir informações na documentação
- [x] Alterar a nomeação da 'frequência de ocorrências por página'. Na verdade, se trata de quantidades de páginas necessárias para o apareceimento de uma ocorrência.
- [x] Nomeção do relatório `infos_acervos_{{período}}_page01`: 
   - [x] Não leva em consideração diferentes locais com mesmo período e termo de busca. Com isso, salva por cima de relatório anterior.
   - [x] Remover espaços no período. Exemplo: `1880 - 1889` para `1880-1889`
- [x] Nomeação dos relaórios de acervos `relatório_{{nome-do-acervo}}_{{número-do-acervo}}_{{AAAA-MM-DD}}_{{HH-MM-SS}}`:
   - [x] Remover espaços no nome do acervo
   - [x] Remover caracteres especiais
- [x] Corrigir Bug na busca: headless não carrega a página corretamente (ver issue #17 e #18 )
- [x] Aviso de jornal com restições: padronizar texto.

**Comment by ericbrasiln** [comment]
Para corrigir o bug referenciado nas issues #17 e #18:

O argumento --headless agora é utilizado como '--headless=new' e segundo a documentação do Selenium:

>Using --headless=new should bring a better experience when using headless with Selenium.

Veja o post completo [aqui](https://www.selenium.dev/blog/2023/headless-is-going-away/) e essa [resposta no StackOverflow)(https://stackoverflow.com/questions/45631715/downloading-with-chrome-headless-and-selenium/73840130#73840130)
