### ISSUE TITLE
Problema no parâmetro "termo da busca": termos sem o uso de `"` como delimitador retorna erro

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/pyHDB#8]
## Descrição do erro

Ao buscar termos sem a utilização de aspas duplas para definir expressões exatas, o programa está retornando o seguinte erro:

```
Traceback (most recent call last):
  File "/home/ebn/Documentos/test_pyHDB/pyHDB/src/pyHDB.py", line 115, in <module>
    set_journal(driver, journal)
  File "/home/ebn/Documentos/test_pyHDB/pyHDB/src/parameters.py", line 51, in set_journal
    p_arrow = WebDriverWait(driver, 40).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="PeriodicoCmb3_Arrow"]'))).click()
  File "/home/ebn/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ebn/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 740, in _execute
    return self._parent.execute(command, params)
  File "/home/ebn/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/ebn/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span id="PeriodicoCmb3_Arrow" class="p-icon p-i-arrow-60-down"></span> is not clickable at point (773, 162). Other element would receive the click: <div class="raDiv">...</div>
  (Session info: headless chrome=102.0.5005.115)
Stacktrace:
#0 0x558340f63f33 <unknown>
#1 0x558340cae118 <unknown>
#2 0x558340ceba42 <unknown>
#3 0x558340ce95f2 <unknown>
#4 0x558340ce6c74 <unknown>
#5 0x558340ce58c5 <unknown>
#6 0x558340cd95b9 <unknown>
#7 0x558340d01f72 <unknown>
#8 0x558340cd8e73 <unknown>
#9 0x558340d0207e <unknown>
#10 0x558340d152e4 <unknown>
#11 0x558340d01e63 <unknown>
#12 0x558340cd782a <unknown>
#13 0x558340cd8985 <unknown>
#14 0x558340fa84cd <unknown>
#15 0x558340fac5ec <unknown>
#16 0x558340f9271e <unknown>
#17 0x558340fad238 <unknown>
#18 0x558340f87870 <unknown>
#19 0x558340fc9608 <unknown>
#20 0x558340fc9788 <unknown>
#21 0x558340fe3f1d <unknown>
#22 0x7f6d4df3db43 <unknown>
```

Quando a busca é realizada por expressões exatas (com `"` como delimitador) a ferramenta funciona corretamente até para mais de três termos.

## TODO

- [x] Realizar debug e encontrar o erro
- [x] Corrigir e testar
- [x] Documentar
- [x] Incluir recomendações de uso na documentação
- [ ] Fazer PR e fazer novo release com a tag v1.5.1

**Comment by ericbrasiln** [comment]
O erro da linha 51 da função `set_journal`, no arquivo `parameters.py` não está relacionado com o tipo de termo usado para a busca. 

Esse erro acontece em função de problemas de carregamento da página da HDB e não está relacionado com a ferramenta. 

Buscando evitar que esses erros aconteçam e, se acontecerem, que sejam exclarecidos para os usuários, encaminhei a solução em duas etapas:
1. Excluí cliques extras na função `set_journal` no PR #10 
2. Inclusão de validações em cada função do arquivo `parameters.py`. Caso erros acontecam, uma mensagem aparece e o programa é encerrado.
